version: '3.8'

services:
  app:
    image: mehmettalha/awsdocker:latest
    build: .
    ports:
      - "9090:8080"
    depends_on:
      - db
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/swe304docker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 61611616
      SERVER_PORT: 8080  # İç port 8080 olarak kalmalı

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: swe304docker
      MYSQL_ROOT_PASSWORD: 61611616
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  mysql-data: