name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository'i checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. JDK kurulumu
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle ile JAR dosyası oluşturma
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      # 4. Docker image oluşturma
      - name: Build Docker image
        run: |
          docker build -t mehmettalha/awsdocker:latest .
          docker build -t mehmettalha/awsdocker:${{ github.sha }} .

      # 5. DockerHub'a login
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Docker image'i DockerHub'a push
      - name: Push Docker image to DockerHub
        run: |
          docker push mehmettalha/awsdocker:latest
          docker push mehmettalha/awsdocker:${{ github.sha }}

      # 7. AWS EC2'ye yapılandırma dosyalarını kopyalama
      - name: Copy configuration files to AWS
        uses: appleboy/scp-action@master
        with:
          host: ec2-107-21-155-238.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.CLOUD_SSH_KEY }}
          source: "docker-compose.yml,nginx.conf,Dockerfile"
          target: "/home/ubuntu"

      # 8. AWS'de uygulamayı yeniden başlatma
      - name: Update and restart application on AWS
        uses: appleboy/ssh-action@master
        with:
          host: ec2-107-21-155-238.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.CLOUD_SSH_KEY }}
          script: |
            cd /home/ubuntu
            
            # Önceki konteynerleri durdur
            docker-compose down || true
            
            # Docker imajını güncelle
            docker pull mehmettalha/awsdocker:latest
            
            # Uygulamayı başlat
            docker-compose up -d
            
            # Durum kontrol
            docker ps
            
            echo "Uygulama başarıyla güncellendi ve yeniden başlatıldı"