name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository'i checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. JDK kurulumu
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle ile JAR dosyası oluşturma
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      # 4. Docker image oluşturma
      - name: Build Docker image
        run: |
          docker build -t mehmettalha/awsdocker:latest .
          docker build -t mehmettalha/awsdocker:${{ github.sha }} .

      # 5. DockerHub'a login
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Docker image'i DockerHub'a push
      - name: Push Docker image to DockerHub
        run: |
          docker push mehmettalha/awsdocker:latest
          docker push mehmettalha/awsdocker:${{ github.sha }}

      # 7. AWS EC2'ye yapılandırma dosyalarını kopyalama
      # (script kullanarak SSH yöntemiyle)
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CLOUD_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-107-21-155-238.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      - name: Copy files and restart application
        run: |
          # Dosyaları kopyala
          scp -o StrictHostKeyChecking=no docker-compose.yml nginx.conf Dockerfile ubuntu@ec2-107-21-155-238.compute-1.amazonaws.com:/home/ubuntu/
          
          # Uygulamayı yeniden başlat
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-107-21-155-238.compute-1.amazonaws.com << 'EOF'
            cd /home/ubuntu
            docker-compose down || true
            docker pull mehmettalha/awsdocker:latest
            docker-compose up -d
            echo "Uygulama başarıyla güncellendi ve yeniden başlatıldı"
            docker ps
          EOF